
// This file is automatically generated by the Firebase-Tools plugin.
/* eslint-disable */
export const firebaseConfig = {
  "apiKey": "AIzaSyAoekKx8d8s7HgskzW1iirid9HtPMp8bew",
  "authDomain": "nova-s-braid-game.firebaseapp.com",
  "projectId": "nova-s-braid-game",
  "storageBucket": "nova-s-braid-game.appspot.com",
  "messagingSenderId": "250398557195",
  "appId": "1:250398557195:web:ccc091fd7fcf05babd330e",
  "measurementId": "G-T49632128P"
};
